name: andrew
favicon: null
layout_spectrum: 0.206926
typography_spectrum: 0.782939
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#90B0C0'
    - '#5D5428'
    - '#607890'
    - '#B8A858'
    - '#000000'
  brandStrength: 0.155476
  lightness: 0.077102
  saturation: 0.20433
  rhythmicContrast: 0.116265
purpose:
  - name: null
    item: null
    url: null
